package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JhipsterSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJhipsterSettingAllPropertiesEquals(JhipsterSetting expected, JhipsterSetting actual) {
        assertJhipsterSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertJhipsterSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJhipsterSettingAllUpdatablePropertiesEquals(JhipsterSetting expected, JhipsterSetting actual) {
        assertJhipsterSettingUpdatableFieldsEquals(expected, actual);
        assertJhipsterSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJhipsterSettingAutoGeneratedPropertiesEquals(JhipsterSetting expected, JhipsterSetting actual) {
        assertThat(expected)
            .as("Verify JhipsterSetting auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJhipsterSettingUpdatableFieldsEquals(JhipsterSetting expected, JhipsterSetting actual) {
        assertThat(expected)
            .as("Verify JhipsterSetting relevant properties")
            .satisfies(e -> assertThat(e.getTheme()).as("check theme").isEqualTo(actual.getTheme()))
            .satisfies(e -> assertThat(e.getPageSize()).as("check pageSize").isEqualTo(actual.getPageSize()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJhipsterSettingUpdatableRelationshipsEquals(JhipsterSetting expected, JhipsterSetting actual) {
        assertThat(expected)
            .as("Verify JhipsterSetting relationships")
            .satisfies(e -> assertThat(e.getJhipster()).as("check jhipster").isEqualTo(actual.getJhipster()));
    }
}
